# Generated by Django 5.2.5 on 2025-09-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
