# Generated by Django 5.2.5 on 2025-10-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_taxcalculation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxCalculation',
        ),
    ]
