# Generated by Django 5.2.5 on 2025-10-02 20:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_type', models.CharField(choices=[('resident', 'Resident'), ('senior', 'Senior Citizen'), ('nri', 'Non-Resident Indian'), ('huf', 'HUF')], default='resident', max_length=20)),
                ('regime', models.CharField(choices=[('old', 'Old Regime'), ('new', 'New Regime')], default='old', max_length=10)),
                ('gross_income', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('tds', models.FloatField(default=0)),
                ('deductions', models.JSONField(default=dict)),
                ('has_business', models.BooleanField(default=False)),
                ('presumptive', models.BooleanField(default=False)),
                ('special_income', models.BooleanField(default=False)),
                ('total_tax', models.FloatField(blank=True, null=True)),
                ('taxable_income', models.FloatField(blank=True, null=True)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
