# Generated by Django 5.2.5 on 2025-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculate', '0002_alter_taxcalculation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculation',
            name='user',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
