# Generated by Django 5.2.5 on 2025-10-02 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculate', '0003_alter_taxcalculation_user'),
        ('users', '0004_delete_taxcalculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_calculations', to='users.useraccount'),
        ),
    ]
