# Generated by Django 5.2.5 on 2025-10-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculate', '0008_faq_category_faq_updated_at_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
