# Generated by Django 5.2.5 on 2025-10-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculate', '0009_faq_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
