# Generated by Django 5.2.5 on 2025-10-30 10:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('reset_token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tab.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='TaxCalculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taxpayer_type', models.CharField(max_length=100)),
                ('regime', models.CharField(max_length=100)),
                ('gross_income', models.FloatField()),
                ('age', models.IntegerField()),
                ('tds', models.FloatField()),
                ('deductions', models.JSONField()),
                ('total_tax', models.FloatField()),
                ('taxable_income', models.FloatField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_calculations', to='tab.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='EmailService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='tab.useraccount')),
            ],
        ),
    ]
